### ISSUE TITLE
Failed to call constructor

### ISSUE THREAD

**Issue by Shamshu1** [Korzer420/LoreMaster#13]
Hello, the mod can`t be loaded (both the latest release and earlier ones)
![image](https://user-images.githubusercontent.com/88609547/200668708-13bc8c7a-d4d9-47ed-89b7-6217165ee124.png)
![image](https://user-images.githubusercontent.com/88609547/200668737-79d9d824-d0d6-4956-bf56-2a9c41b3983e.png)

**Comment by Korzer420** [comment]
Hey, I can't reproduce the problem.  :/ 

On which system do you play? (Windows, Mac or Linux) And can you check if there is a "Lore.png" file somewhere inside the Resources\Base folder?

**Comment by Shamshu1** [comment]
Linux
![image](https://user-images.githubusercontent.com/88609547/200897347-eaa67711-6b36-44ed-bf5e-271f3a8e6ae8.png)
![image](https://user-images.githubusercontent.com/88609547/200896996-116e27a5-1449-4f96-9852-db15d2c3b71a.png)

**Comment by Korzer420** [comment]
Hm, I suspect the "/" could be a problem here. In the path you can see that the last part "Resources\Base" actually has backslashes instead of normal ones. I'm not familiar with Linux sorry. Here's a version which uses normal slashes instead. It might still be missing ones, but for a quick test it should be enough. Delete the .pdb and dll files and use these instead. Does this work? (This does NOT contain the resource folder since I can only upload up to 25 mb here.
[LoreMaster.zip](https://github.com/Korzer420/LoreMaster/files/9974363/LoreMaster.zip)

**Comment by Shamshu1** [comment]
After using new files, new error appears:
![Снимок экрана от 2022-11-09 22-23-32](https://user-images.githubusercontent.com/88609547/200923944-92b64193-36f3-4ced-a859-198741641e3e.png)
but I just renamed these files .PNG -> .png
![Снимок экрана от 2022-11-09 22-24-45](https://user-images.githubusercontent.com/88609547/200923050-89234b74-6abe-4bc3-b76d-8c23ac8cb06b.png)
and it works now (at least at first sight)
![Снимок экрана от 2022-11-09 22-19-28](https://user-images.githubusercontent.com/88609547/200924129-98c58765-b359-4d23-b746-86e599bc24fb.png)
![image](https://user-images.githubusercontent.com/88609547/200923760-cd00a6ae-f3dd-44e1-93ae-d604e1769a0d.png)
btw some errors are still there, but I dont think it matters too much
![Снимок экрана от 2022-11-09 22-24-19](https://user-images.githubusercontent.com/88609547/200925052-91dc42cb-04e7-4df0-974d-6d4abfe5f762.png)

**Comment by Korzer420** [comment]
Will update the path and the names of the extensions. 
For the last part it seems that the global settings were missing/corrupted. I can add a safety check for that. But it "should" only affect the tags if you changed them. Though if you don't play the extra mode (which might not even have appeared for you due to this), this doesn't matter.
Will be updated in the next 2 days. Thank you <3
