### ISSUE TITLE
Player character stop permanently unless I restart game or character takes damage.

### ISSUE THREAD

**Issue by abcde111112** [Korzer420/LoreMaster#25]
When I play with Hard (with cursed lore 60) and break quickly some structures in succession in Crossroads, Player character stop permanently
unless
- I restart game or
- character takes damage by enemy or
- open and close Inventory button

is it intended? I think it is negative effect of Best Mender In The World Power, which is appeared when I don't possess this.

**Comment by Korzer420** [comment]
(Copy pasted from Issue #27 )
Hey there, sorry you encountered these issues. The whole twisted effect system was kinda rushed and I wasn't very eagier to work at modding as a whole. Since currently the whole mod is reworked (where the twisted system will be removed (for an unseeable future)) unfortunately I don't can/want to further support the twisted powers.

So this whole mode shouldn't be used at the moment.

In case at some point if I revisited the idea I'll keep these reports in mind and fix them. But don't count on that. Sorry :(
