### ISSUE TITLE
[Bug list?] Please check these..,

### ISSUE THREAD

**Issue by abcde111112** [Korzer420/LoreMaster#26]
- Power: Eternal Valor
What is cooldown time of negative effect of Power of Eternal Valor?
I find it description: `Hitting an enemy does generate a stack up to 24. After not hitting an enemy for 3 seconds a stack will go away each 1 second. If enemies you damaged, are still alive once all stacks ran out, you take 2 damage.`
But this effect, when I firstly load the saved game and only have one-time effect. after causing that negative effect, this effect does not work in game no longer.
Only it is retriggered when game restart (not saved file restart)

- Power: Camouflage
  it's twisted version: The knight is invisible. but truly not works. I've checked (color.a = 1) from sources. // causes  player opaque.

**Comment by Korzer420** [comment]
(Copy pasted from Issue #27 )
Hey there, sorry you encountered these issues. The whole twisted effect system was kinda rushed and I wasn't very eagier to work at modding as a whole. Since currently the whole mod is reworked (where the twisted system will be removed (for an unseeable future)) unfortunately I don't can/want to further support the twisted powers.

So this whole mode shouldn't be used at the moment.

In case at some point if I revisited the idea I'll keep these reports in mind and fix them. But don't count on that. Sorry :(
