### ISSUE TITLE
Please adjust balance  of spawned enemy when play with hard mode or twisted.

### ISSUE THREAD

**Issue by abcde111112** [Korzer420/LoreMaster#27]
- for All mob by Powers
When player interact something by system, and if player is attacked by mob, only Text box remains but text is none. If I retry interact, most action is stuck.

- Grasp of Life (⛑️ debuff by mob:  Walking on the ground for 2 seconds, spawn a fool eater under you.)
      Fool eaters are spawned very too fast. even it is spawned when player is midair by crystal dash.
      and If with We don't talk about the Shade Power, it causes creating infinite mobs. (⛑️ Every enemy spawns a sibling upon death. Even with void heart, it stays aggressive.)

- Marissas Audience
  the revek is so powerful, specially attack speed. but It is not removed for cooldown time when player attack this, so the mob revives right.

- Delicious Meal
  Poggy must be eaten rancid egg periodically , but inventory control is impossible during fight (Any have something hot key?).
  and I can not buy rancid eggs because I have don't money. this is caused by following two negative power synergies.
  - True Form
(  ⛑️ Spawns a shade every 2 minutes, taking all your geo and fleeing to the exit where you entered from.)
  -  Mindblast of Unn
(  ⛑️ Enemies cannot be hit until you dream nail them. If you don't have dream nail all enemies have triple their health.    )

**Comment by Korzer420** [comment]
Hey there, sorry you encountered these issues. The whole twisted effect system was kinda rushed and I wasn't very eagier to work at modding as a whole. Since currently the whole mod is reworked (where the twisted system will be removed (for an unseeable future)) unfortunately I don't can/want to further support the twisted powers.

So this whole mode shouldn't be used at the moment.

In case at some point if I revisited the idea I'll keep these reports in mind and fix them. But don't count on that. Sorry :(
