### ISSUE TITLE
Randomizer 4 Compatibility Issue

### ISSUE THREAD

**Issue by Zitialien** [Korzer420/LoreMaster#28]
Hey Korz!

I saw Fireb0rn's stream vod on his YouTube channel today playing your mod. I really loved the work you put into making all the powers work and especially the personality you put into the custom lore text. I downloaded the mod and tried to experience it for myself (fireb0rn skipped so many lore tablets) but unfortunately ran into this issue. There also seems to be other people running into the same issue on the discord server and I learned from there that it's a compatibility issue.

I would really love to try out your mod with Randomizer 4 one day! I shall await your return, much appreciated~

![Randomizer 4 x Lore Master Error](https://github.com/Korzer420/LoreMaster/assets/64550765/909a3024-8d3c-4447-9099-ca7c95a7eb45)

**Comment by Korzer420** [comment]
Hey there, at the start of februar an update to randomizer 4 happened (not adding anything new for frontend users, just like for connection developers). Since then, most connections broke due to this, but updated quickly. As the mod is currently under a complete rework I unfortunately can't create an easy fix for this issue sorry.

If you want to use the powers/mod anyway. You would need to downgrade Randomizer 4, its dependencies and all other connections to a version before February 2nd.

I expect the rework to take multiple weeks at this paste. until then, this is your only option, sorry :(

**Comment by ZitialienX** [comment]
Don’t be sorry! I respect modders a great deal because of their passion for the game. The work you’ve put in is a gift for us. I’m actually really excited (to hear and) to see this rework you’re working on. 

Thank you for the solution you’ve given for the meantime. I just wanted to ask due to my curiosity as I have no idea where to seek the information I needed. 

Please take your time and most importantly remember to take care of yourself :D

**Comment by Zitialien** [comment]
Don’t be sorry! I respect modders a great deal because of their passion for the game. The work you’ve put in is a gift for us. I’m actually really excited (to hear and) to see this rework you’re working on. 

Thank you for the solution you’ve given for the meantime. I just wanted to ask due to my curiosity as I have no idea where to seek the information I needed. 

Please take your time and most importantly remember to take care of yourself :D
